# Continuous Integration (CI) is the practice, in software
# engineering, of merging all developer working copies with a shared mainline
# several times a day < http://docs.platformio.org/en/latest/ci/index.html >
#
# Documentation:
#
# * Travis CI Embedded Builds with PlatformIO
#   < https://docs.travis-ci.com/user/integration/platformio/ >
#
# * PlatformIO integration with Travis CI
#   < http://docs.platformio.org/en/latest/ci/travis.html >
#
# * User Guide for `platformio ci` command
#   < http://docs.platformio.org/en/latest/userguide/cmd_ci.html >
#

language: python
python:
    - "2.7"

# Trusty gives us a modern GCC - important for C++ 11 support
dist: trusty

sudo: false
cache: pip

install:
    - pip install -U platformio cpp-coveralls
    - pip install -r src/sktool/requirements.txt

script:
    # This builds all the targets compatible with travis
    # we do not build sktooljs on travis at the moment
    - platformio run -e host -e esp -e program-esp -e mfg -e sktool -e test
    # Run the few unit tests (C code running on computer)
    - make test
    # Run the sktool-test.py script to validate that SignalK output is valid and
    # matches what we expect.
    - make validation

after_success:
    - coveralls --exclude src/test --exclude /lib --exclude lib --exclude .piolibdeps

deploy:
  provider: releases
  api_key:
    secure: QYe/1yIJZbSe5uZfoCROTT7s+1Yhe0lY1Ww8Ia//yYMQOYjvkjY+UAHaZ7FN+X3MBHPcMQCEPxeG4Hmy7fvTTV2nIRPlkheirZqSYt7HYr9WdbA/N29F92o/EMT5nQgqfmOf9u61Hx5K3JLyBnLIilajOpnHgARJXgg7w8lC2hE57k9oO0PWlFLGrNZRa9xfHeHnrOVL90TW3sk6/YR6J5u+cg2ZMwFPs8PPCxw/cBDowvQ3JrXrrQwRxHiAnrTscYlHoFEidsAAnrL99GROiRgFEGYQhddilztQ/h52AUy9+QDxAlVgxV/hi1+AUOGeeSK4GQPugrfH1+3kTR4a6T/XdTBoydTQSUYTHU4PcKJwzoaEwOVGVr4lg0Fl5ZCktcPLlY+TBHfBfitPAaNujWTA5P/pUv3Vwdq5pX4xYfhqFKIqZohlDOYEhk0xtAYvlYB4teaLCGkPNjtBi+8e11FghdaSZ/G6vXCkvGeOPrSIcp9g4pwnpwwhMMJISdpnpxm5cSLZJBOAJybsYUIPjVtjfvAQ6e0GpvcQsePDFBz6qSFSvYIpgEBE8gOcNotWHyiHjCkV4aAm+mBFmJ5Ndfr6XMSK+uARWG98FRrGNN4HZJl3h7cRrd2f1cOIm9N7SWLIXmMwEMYyIq+X++ZCKqOMhFnw3THhFxZ+U5ACOQM=
  file:
    - ".pioenvs/host/firmware.elf"
    - ".pioenvs/host/firmware.hex"
    - ".pioenvs/esp/firmware.elf"
    - ".pioenvs/esp/firmware.bin"
    - ".pioenvs/sktool/program"
  skip_cleanup: true
  on:
    repo: sarfata/kbox-firmware
    branch: master
    tags: true