# Continuous Integration (CI) is the practice, in software
# engineering, of merging all developer working copies with a shared mainline
# several times a day < http://docs.platformio.org/en/latest/ci/index.html >
#
# Documentation:
#
# * Travis CI Embedded Builds with PlatformIO
#   < https://docs.travis-ci.com/user/integration/platformio/ >
#
# * PlatformIO integration with Travis CI
#   < http://docs.platformio.org/en/latest/ci/travis.html >
#
# * User Guide for `platformio ci` command
#   < http://docs.platformio.org/en/latest/userguide/cmd_ci.html >
#

language: python
python:
    - "2.7"

dist: trusty
sudo: false
cache:
    directories:
        - "~/.platformio"

install:
    - pip install -U platformio

script:
    # This builds all the target
    - platformio run
    # Run the few unit tests (C code running on computer)
    - make test

# required to get a modern version of g++ with full std-c11 support
#env:
  #CC=gcc-4.9
  #CXX=g++-4.9
#addons:
  #apt:
    #sources:
    ## add PPAs with more up-to-date toolchains
    #- ubuntu-toolchain-r-test
    #packages:
    ## install toolchains
    #- gcc-4.9
    #- g++-4.9
